config/routes.rb
Dribbble::Application.routes.draw do
  
  root "main#index"
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :shots, only: [:show]
   
    
  match "/signup", to: "users#new", via: "get"
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  
  get "pagination/:page"=> 'pagination#next'
 

  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token 
  
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                   
                    
  has_secure_password
  validates :password, length: { minimum: 6 }, if: :should_validate_password?
  

  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def User.digest(token)#encrypt token
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  private
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
   private
    def  should_validate_password?##only validates password if it is an new user
       new_record?
    end 
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
  include UsersHelper

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index  
    if signed_in?   
      @shots=Dribbble::Shot.popular(:page => 1, :per_page => 24)
      @page=1;
    else
      redirect_to signin_path
    end
  end  
end

app/controllers/pagination_controller.rb
class PaginationController < ApplicationController
  layout "blank", only: [:next] 
  def next
    @page=params[:page]
    @shots=Dribbble::Shot.popular(:page => @page, :per_page => 24)
  end
  
  private
    def paginateParams
      params.permit(:page)
    end  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if signed_in? 
      redirect_to root_path
    else #not signed in
      render :new    
    end    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session] [:password])
      sign_in user
      redirect_to root_path
    else
      flash[:messages] = {warning: 'Invalid email/password combination'}
      render 'new'
    end  
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  layout "blank", only: [:show]  
  def show
    @shot=Dribbble::Shot.find(params[:id].to_i)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  layout "blank", only: [:edit, :update] 
  
  def index
    if is_admin?
      @users=User.all()
    else
      redirect_to root_path
    end
  end
  
  def edit
    if is_admin?
      @user=User.find(params[:id])
      render template: "users/edit"
    end  
  end  
  
  def update
    if is_admin?
        @user=User.find(params[:id])
        @user.update(update_user_params)
        flash[:messages] = {success: "Usuario editado com succeso!"}
        redirect_to users_path
    elsif  @current_user.id == params[:id] && signed_in? 

    end
  end

  def  destroy
    if is_admin?
      @user=User.find(params[:id]).destroy
      if @user.destroyed?
        flash[:messages] = {success: "Usuario apagado"}
        redirect_to users_url
      end
    end
  end
  
  def new
    @user=User.new
  end
  
  def home
  end
  
  def show
    if signed_in? 
    else
      redirect_sign_in     
    end    
  end
  
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:messages] = {success: "casdastro ok!"}
      #UserJob.new.async.welcome(@user) #jobs/user_job
      #UserJob.new.async.notify_admin_new_user(@user) 
      #@admin=User.find_by!(role: "admin")
      #UserMailer.notify_admin_new_user(@user, @admin)
      
      redirect_to root_path
    else
     render 'new'   
    end
  end
  
  private
    def user_params
      params.require(:user).permit(
                      :name, 
                      :email, 
                      :password, 
                      :password_confirmation
                      )

    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title (page_title)
    base_title="Desafio "
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pagination_helper.rb
module PaginationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token=User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end
  
  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def redirect_sign_in
      flash[:error] = "must be logged in"
      redirect_to signin_path
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user
  end
  
  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)#if current user nil = find it and assign 
  end
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/layouts/_header.html.erb
<nav class="main-header navbar ">
	<div class="container">	
		
	  <div class="navbar-header">
	  	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-content" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
	  	<a id="logo" class="navbar-brand" href="<%= url_for root_path %>" name="Desafio Dribbble" >
	  		<img alt="dribbble" src="https://d13yacurqjgara.cloudfront.net/assets/logo-small-c1d9a9e90643192d4835730985b4b65c.png">
	  	</a>
	  	
	  </div>
		
			
	  <div class=" collapse navbar-collapse  " id="menu-content" role="navigation">
	  	
	    <ul class="nav navbar-nav navbar-right">
	  		<li><%= link_to "Home",    root_path %></li>
	  		<% if signed_in? %>
	  		
	  			<li class="dropdown">
	  				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		  				<span class="glyphicon glyphicon-user"></span>	
		  				Olá <%= @current_user.name %><span class="caret"></span>
	  				</a>
	  				<ul class="dropdown-menu" role="menu">
	  					<li><%= link_to "Log out", signout_path, method: "delete" %></li>
	  				</ul>
				</li>
				
	  		<%else %><%# if signed in %>
				<li><%= link_to "Log in", '/signin' %></li>
			<% end%>
		</ul>
	  </div>
	  
	  
	</div>
</nav>

app/views/layouts/_lightbox.html.erb
<div id="ligthbox">
	<div class="overlay close-lightbox"></div>
	<div class="shot-container center">
		
	</div>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta http-equiv="X-UA-Compatible"  content="IE=edge,chrome=1">
    <meta name="viewport"  content="width=device-width, initial-scale=1.0">

    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>  	
	 <%= render :partial => 'layouts/header' %>	
    <div class="container main-container">     
     <%= yield %>
     <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render :partial => 'layouts/lightbox' %>	
  </body>
</html>

app/views/layouts/blank.html.erb
<%=yield%>

app/views/main/index.html.erb
<% provide(:title, 'Dribbble') %>

<div class="row">
	<div class="col-xs-12 col-sm-11 col-md-12  center list-cont">
		<%= render :partial => 'shared/list_shots' %>		
		<div class="clear"></div>
		<a class="center next-page" href="/pagination/2">next</a>
	</div>
</div>

app/views/pagination/next.html.erb
<%= render :partial => 'shared/list_shots' %>	

<a class="center next-page" href="pagination/<%=@page.to_i+1%>">next</a>	
<script type="text/javascript">document.ligthBox( $('#shots-page_<%=@page%>').find('.shot') )</script>

app/views/shared/_error_messages.html.erb
<% if !model.nil? && model.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      Tem <%= pluralize(model.errors.count, "error") %>.
    </div>
    <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
  	<% if !flash[:messages].nil? %>
	  	<% flash[:messages].each do |key, value| %>
	       <%= content_tag(:div, value, class: "alert alert-#{key}") %>
	    <% end %>
    <% end %>

app/views/shared/_list_shots.html.erb
<ul class="list-inline dribbble-list" id="shots-page_<%=@page%>">
	<% @shots.each do |s|%>
		<li class="col-xs-6 col-sm-4 shot" data-shot="<%= s.id %>" >
			<figure>
				<img src="<%= s.image_url %>" />
				<div class="meta">
					<ul class="list-inline">
						<li><%= fa_icon "eye"%> <%= s.views_count %></li>
						<li><%= fa_icon "comment-o"%> <%= s.comments_count %></li>
						<li><%= fa_icon "heart-o"%> <%= s.likes_count %></li>
					</ul>
				</div>
				<div class="overlay">
					<h2><%= s.title %></h2>
					<% desc = strip_tags (raw s.description) %>
					<div class="description"><%= truncate(desc, :length => 100, :separator => ' ',:escape=>false)%></div>
				</div>
			</figure>
		</li>
	<% end %>
</ul>

app/views/shots/show.html.erb
<figure><img src="<%= @shot.image_url %>"></figure>
<div class="shot-data">
	<div class="player">
		<span class="avatar">
			<img src="<%= @shot.player.avatar_url %>" >
		</span>
		<span class="player-name"><%= @shot.player.name %></span>
	</div>
	<h2><%= @shot.title %></h2>
	<div class="decription"><%= raw @shot.description %></div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>


<div class="row">
  <div class="col-xs-12  col-sm-4 centered">
  	<h1 class="section-title center">Cadastro</h1>
	<%= form_for(@user, html: {class:'user-form'}) do |f| %>
	 
	  <%= render :partial => 'shared/error_messages',  :locals => {:model => @user} %>	
	  <div class="form-group">			
		  <%= f.label :name, "Nome" %>
		  <%= f.text_field :name, class: "form-control" %>
	  </div>
	  
	  <div class="form-group"> 		
		  <%= f.label :email %>
		  <%= f.text_field :email, class: "form-control" %>
	  </div>
	  
	  <div class="form-group">
		  <%= f.label :password, "Senha" %>
		  <%= f.password_field :password, class: "form-control" %>
	  </div>
	  
	  <div class="form-group">
		  <%= f.label :password_confirmation, "Repete senha" %>
		  <%= f.password_field :password_confirmation, class: "form-control" %>
	  </div>
	  
	  <div class="form-group">
	  	<%= f.submit "Criar Conta", class: "btn btn-large btn-primary" %>
	  </div>
	<% end %>
  </div>
</div>